### ISSUE TITLE
Missing negedge N_RESET

### ISSUE THREAD

**Issue by alexm2033** [UniversityOfPlymouth-Electronics/DigitalSystems#20]
module counterN #(parameter N=8) (output logic [N-1:0] Y, input logic CLK, input logic N_RESET);

logic [N-1:0] count;

//Connect output to internal register count
assign Y = count;

always_ff @(posedge CLK) begin
	if (N_RESET == 0) 
		count <= 0;
	else
		count <= count + 1;
end

endmodule

**Comment by noutram** [comment]
Fixed - with thanks!

**Comment by noutram** [comment]
Now fixed in the notes (to mirror the example code)
