### ISSUE TITLE
Finite State Machines - Moore Machines

### ISSUE THREAD

**Issue by Macaw21** [UniversityOfPlymouth-Electronics/DigitalSystems#21]
https://github.com/UniversityOfPlymouth-Electronics/DigitalSystems/blob/main/level5/finite_state_machines.md#moore-machines

Image "push_release_FSM_cct.png" is incorrect.  JKFF inputs J and K appear to be connected to the clock due to the presence of a node.

**Comment by noutram** [comment]
I belive this is now corrected. Many thanks and well spotted.
